version: '3.7'

services:

  wireguard:
    # Created by following https://containers.fan/posts/wireguard-vpn-on-docker/
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=wireguard.peterhenry.net
      - SERVERPORT=51820
      - PEERS=simone,nawa
      # - PEERDNS=192.168.0.114
      # - INTERNAL_SUBNET=10.64.1.0
      # - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - type: bind
        source: ./config/wireguard
        target: /config
      - type: bind
        source: /lib/modules
        target: /lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

  nginxproxymanager:
    # Created by following https://nginxproxymanager.com/setup/#running-the-app
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - type: bind
        source: ./data/nginxproxymanager/data
        target: /data
      - type: bind
        source: ./data/nginxproxymanager/letsencrypt
        target: /etc/letsencrypt
